name: Deploy QuidditchTrip.Client 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      # Cache node modules for faster builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          cd QuidditchTrip.Client
          npm install

      - name: Build the project
        run: |
          cd QuidditchTrip.Client
          npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH }} 

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "echo Hello World"

      - name: Deploy to EC2
        run: |
          rsync -avz  -o StrictHostKeyChecking=no" QuidditchTrip.Client/dist/ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/srv/Quidditch.Client

      - name: Restart Caddy
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart caddy"
